# Generated by Django 3.2.9 on 2021-11-24 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimId', models.SmallIntegerField()),
                ('frontTire', models.CharField(max_length=32)),
                ('frontWidth', models.SmallIntegerField()),
                ('frontFlatnessRatio', models.SmallIntegerField()),
                ('frontStruct', models.CharField(max_length=16)),
                ('frontWheelSize', models.SmallIntegerField()),
                ('rearTire', models.CharField(max_length=32)),
                ('rearWidth', models.SmallIntegerField()),
                ('rearFlatnessRatio', models.SmallIntegerField()),
                ('rearStruct', models.CharField(max_length=16)),
                ('rearWheelSize', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
