# Generated by Django 3.2.9 on 2021-11-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20211124_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='frontFlatnessRatio',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='frontWheelSize',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='frontWidth',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='rearFlatnessRatio',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='rearWheelSize',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='rearWidth',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
